### PR TITLE
Add more table flips

### PR DESCRIPTION
**Pull request by danmakenoise**
Created an Array of Table Flips as `Exception::TABLE_FLIPS`

`Exception#to_s` now interpolates a random sample from that Array.

### CODE REVIEW

**Comment by danmakenoise** [comment]
Should be good to go now! Sorry, new to github collaboration.

**Comment by DNNX** [comment]
@iridakos would you mind having a look, please?

**Comment by iridakos** [comment]
@DNNX @danmakenoise I like your change but I was hoping to keep the functionality as simple as possible.

**Comment by danmakenoise** [comment]
No problem!

**Pull request closed without merging**
